version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "9000:9000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "3000:80"